### ISSUE TITLE
iFrames cause issues with DOM notifications

### ISSUE THREAD

**Issue by TravFitz** [TravFitz/Firefox-On-Screen-Keyboard#1]
When clicking inside an iFrame the keyboard is not recognised as the DOM inside the iFrame is different from the main windows DOM.

**Comment by SpectrumJobs** [comment]
One simple change to your manifest.json will allow the OSK to display inside of frames and iframes.
Note the parameter in the code below: "all_frames":true,

    "content_scripts": [
        {	"all_frames": true,
            "matches": [
                "<all_urls>"
            ],
            "js": ["keyboard.js"],
            "run_at": "document_start"
        }
    ],


I have attached a copy of my version of manifest.json.  I had to rename it manifest-json.txt.

[manifest-json.txt](https://github.com/TravFitz/Firefox-On-Screen-Keyboard/files/3637967/manifest-json.txt)

Thank you for your work on this On Screen Keyboard.  Pretty darned cool.

Alfred Heyman

**Comment by TravFitz** [comment]
I will implement that now and give it a test run, Thanks @SpectrumJobs

**Comment by TravFitz** [comment]
Hi @SpectrumJobs,

That does indeed load it into the iframe, the only issue with it is that it creates a new javascript inside the iframe to load its own keyboard (which means that it gets its auto scaling from the iframe instance not the parent) and as a general rule iframe windows cannot see the source code of the parent as they are loaded as a self contained page within a page. However, there may be a way around it. 

Leave it with me and I will do some more work on it to see if I can get it to implement the keyboard into the parent by notification from the iframe.

Thank you for giving me somewhere to get started!

**Comment by TravFitz** [comment]
Fixed in version 1.7.0
