### ISSUE TITLE
Keyboard Settings

### ISSUE THREAD

**Issue by maxsenft** [TravFitz/Firefox-On-Screen-Keyboard#4]
Hi @TravFitz !

Maybe I'm just blind, but are there any settings that are adjustable? Like an overall extra scaling or adjusting of visible keys? Or: There's a num pad in the sourcecode but I don't see/understand how it is activated?

Best regards,
Max

**Comment by TravFitz** [comment]
Hi @maxsenft,

No I have not implemented a settings page yet, the numpad will automatically be displayed when an numerical input box has been selected (like 'number', 'range', 'tel', 'time' or 'week')

**Comment by TravFitz** [comment]
Hi @maxsenft,

I have implemented a basic properties screen now so that you can adjust the scale of the OSK and also enable or disable (default is to auto-select) the Numpad if you would like.
